import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
    # "~/.config/alacritty/catppuccin-macchiato.toml"
    # "~/.config/alacritty/catppuccin-frappe.toml"
    # "~/.config/alacritty/catppuccin-latte.toml"
]

shell = "/bin/zsh"

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.90
blur = true
startup_mode = "Maximized"
title = "Terminal"
dynamic_title = true
option_as_alt = "OnlyLeft"

[font]
size = 17

[font.normal]
family = "AnonymicePro Nerd Font"
style = "Regular"

[font.bold]
family = "AnonymicePro Nerd Font"
style = "Bold"

[font.italic]
family = "AnonymicePro Nerd Font"
style = "Italic"

[font.bold_italic]
family = "AnonymicePro Nerd Font"
style = "Bold Italic"

